[theme]
primaryColor = "#0070AD"
backgroundColor = "#F5F7FA"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#1B263B"
font = "sans serif"

[server]
maxUploadSize = 200
headless = true

[browser]
gatherUsageStats = false